// Generated by CoffeeScript 1.3.3
(function() {
  var Repository, strategy;

  Repository = require('../repository');

  strategy = function(room_id) {
    return new Repository('ChatRoom').get_by_id(room_id);
  };

  module.exports = strategy;

}).call(this);
