// Generated by CoffeeScript 1.3.3
(function() {
  var mapping;

  mapping = {
    'root_collection': 'pass_through_strategy',
    'user_collection': 'pass_through_strategy',
    'users_collection': 'user_by_username_strategy',
    'user_rooms_collection': 'chat_rooms_by_owner_id_strategy',
    'room_collection': 'chat_room_by_id_strategy',
    'room_members_collection': 'chat_room_by_id_strategy'
  };

  module.exports = mapping;

}).call(this);
