// Generated by CoffeeScript 1.3.3
(function() {
  var mapping;

  mapping = {
    'user_collection': 'pass_through_strategy',
    'room_collection': 'chat_room_by_id_strategy',
    'room_members_collection': 'chat_room_by_id_strategy'
  };

  module.exports = mapping;

}).call(this);
