// Generated by CoffeeScript 1.3.3
(function() {
  var Repository, strategy;

  Repository = require('../repository');

  strategy = function(user_id) {
    return new Repository('User').get_by_id(user_id);
  };

  module.exports = strategy;

}).call(this);
