development:
  adapter: postgresql
  database: dtt_main
  username: postgres
  password: 1234
  host: localhost

test:
  adapter: postgresql
  database: dtt_main
  username: intellisys
  password: welc0me
  host: test_ip

production:
  adapter: postgresql
  database: dtt_main
  username: postgres
  password: welc0me
  host: localhost
  port: 5432
