development:
  adapter: postgresql
  database: dtt_main
  username: postgres
  password: 1234
  host: localhost

test:
  adapter: postgresql
  database: dtt_test
  username: intellisys
  password: welc0me
  host: test_ip

production:
  adapter: postgresql
  database: dtt_main
  username: postgres
  password: welc0me
  host: ec2-107-21-171-44.compute-1.amazonaws.com
  port: 5432
