development:
  adapter: postgresql
  database: dtt_main
  username: postgres
  password: 1234
  host: localhost

test:
  adapter: postgresql
  database: dtt_main
  username: intellisys
  password: welc0me
  host: test_ip

production:
  adapter: postgresql
  database: d9er2dp9rejk7k
  username: huyuuxyveqegxe 
  password: tMU5vspNvcoPxePlBbK5DX1Jvx
  host: ec2-23-21-91-108.compute-1.amazonaws.com
  port: 5432
