nginx:
  host: yacketyapp.com
  api_server_name: api.yacketyapp.com
  port: 3000
  certificates_path: /home/ubuntu/yacketyapp.com/certificates
  public_path: /home/ubuntu/dtt/src/TeamNotification_Server/public
  sites_available_path: /etc/nginx/sites-available/
  sites_enabled_path: /etc/nginx/sites-enabled/

stunnel:
  config_path: /etc/stunnel
  certificates_path: /home/ubuntu/yacketyapp.com/certificates
  default: /etc/default/stunnel4

varnish:
  node_port: 3000
  config_path: /etc/varnish
  default: /etc/default/varnish
