nginx:
  server_host: stagingdtt.local
  api_server_name: api.stagingdtt.local
  server_port: 80
  certificates_path: /home/ubuntu/yacketyapp.com/certificates
  sites_available_path: /etc/nginx/sites-available/
  sites_enabled_path: /etc/nginx/sites-enabled/
