// Generated by CoffeeScript 1.3.3
(function() {
  var UserCollection;

  UserCollection = (function() {

    function UserCollection(user_id) {
      this.set_collection(user_id);
    }

    UserCollection.prototype.set_collection = function(user_id) {
      return this.collection = {
        links: [
          {
            "rel": "self",
            "name": "self",
            "href": "/user/" + user_id
          }, {
            "rel": "rooms",
            "name": "rooms",
            "href": "/user/" + user_id + "/rooms"
          }
        ]
      };
    };

    UserCollection.prototype.fetch_to = function(callback) {
      return callback(this.collection);
    };

    return UserCollection;

  })();

  module.exports = UserCollection;

}).call(this);
