// Generated by CoffeeScript 1.3.3
(function() {
  var UserCollection;

  UserCollection = (function() {

    function UserCollection(data) {
      this.data = data;
    }

    UserCollection.prototype.to_json = function() {
      var room, rooms, self;
      self = "/user/" + this.user_id;
      rooms = (function() {
        var _i, _len, _ref, _results;
        _ref = this.data.rooms;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          room = _ref[_i];
          _results.push(this.get_room(room));
        }
        return _results;
      }).call(this);
      return {
        href: self,
        rooms: rooms,
        links: [
          {
            "rel": "User",
            "name": "self",
            "href": self
          }, {
            "rel": "UserRooms",
            "name": "rooms",
            "href": "/user/" + this.user_id + "/rooms"
          }, {
            "rel": "Room",
            "name": "Create Room",
            "href": "/room"
          }
        ]
      };
    };

    UserCollection.prototype.get_room = function(room) {
      return {
        data: [
          {
            "name": "id",
            "value": room.id
          }, {
            "name": "name",
            "value": room.name
          }
        ],
        links: [
          {
            "rel": "Room",
            "name": room.name,
            "href": "/room/" + room.id
          }
        ]
      };
    };

    return UserCollection;

  })();

  module.exports = UserCollection;

}).call(this);
