// Generated by CoffeeScript 1.3.3
(function() {
  var UserCollection;

  UserCollection = (function() {

    function UserCollection() {}

    UserCollection.prototype.fetch_to = function(callback) {
      return callback(this.value);
    };

    return UserCollection;

  })();

  module.exports = UserCollection;

}).call(this);
