// Generated by CoffeeScript 1.3.3
(function() {
  var passport, passportHttp, repository;

  passport = require('passport');

  passportHttp = require('passport-http');

  repository = require('./repository');

}).call(this);
