// Generated by CoffeeScript 1.3.3
(function() {
  var Authentication, BasicStrategy, exports, passport, repository;

  passport = require('passport');

  BasicStrategy = require('passport-http').BasicStrategy;

  repository = require('./repository');

  Authentication = (function() {

    function Authentication() {
      passport.use(new BasicStrategy({}, this.findByUserName));
    }

    Authentication.prototype.initializeAuth = function() {
      return passport.initialize();
    };

    Authentication.prototype.findByUserName = function(username, password, done) {
      console.log("looking form " + username + ":" + password);
      return done(null, {
        username: 'john'
      });
    };

    Authentication.prototype.authenticate = function(request, response) {
      return passport.authenticate('basic', {
        session: false
      });
    };

    return Authentication;

  })();

  exports = module.exports = Authentication;

}).call(this);
