// Generated by CoffeeScript 1.3.3
(function() {
  var CollectionFactory, mapping;

  mapping = {
    user_collection: './collections/user_collection',
    user_rooms_collection: './collections/user_rooms_collection',
    room_collection: './collections/room_collection',
    room_members_collection: './collections/room_members_collection'
  };

  CollectionFactory = (function() {

    function CollectionFactory(type) {
      this.type = type;
    }

    CollectionFactory.prototype["for"] = function(options) {
      var collection;
      collection = require(mapping[this.type]);
      return new collection(options);
    };

    return CollectionFactory;

  })();

  module.exports = CollectionFactory;

}).call(this);
