// Generated by CoffeeScript 1.3.3
(function() {
  var CollectionFactory, collections_map, path;

  path = require('path');

  collections_map = require('./collections/collections_map');

  CollectionFactory = (function() {

    function CollectionFactory() {}

    CollectionFactory.prototype.get_for = function(type) {
      return this.require_collection(collections_map[type]);
    };

    CollectionFactory.prototype.require_collection = function(collection_path) {
      return require(path.resolve(__dirname, 'collections', collection_path));
    };

    return CollectionFactory;

  })();

  module.exports = CollectionFactory;

}).call(this);
