// Generated by CoffeeScript 1.3.3
(function() {
  var CollectionFactory, Q, Repository, add_user_to_chat_room, build;

  Q = require('q');

  Repository = require('./repository');

  CollectionFactory = require('./collection_factory');

  build = function(collection_type) {
    return new CollectionFactory(collection_type);
  };

  add_user_to_chat_room = function(user_id, room_id) {
    var chat_room_repository, defer, user_repository;
    user_repository = new Repository('User');
    chat_room_repository = new Repository('ChatRoom');
    defer = Q.defer();
    user_repository.get_by_id(user_id).then(function(user) {
      if (user != null) {
        return chat_room_repository.get_by_id(room_id).then(function(chat_room) {
          return chat_room.addUsers(user, function() {
            return defer.resolve("user " + user.id + " added");
          });
        });
      } else {
        return defer.resolve("user " + user_id + " does not exist");
      }
    });
    return defer.promise;
  };

  module.exports = {
    build: build,
    add_user_to_chat_room: add_user_to_chat_room
  };

}).call(this);
