// Generated by CoffeeScript 1.3.3
(function() {
  var CollectionFactory, build;

  CollectionFactory = require('./collection_factory');

  build = function(collection_type) {
    return new CollectionFactory(collection_type);
  };

  module.exports = {
    build: build
  };

}).call(this);
