// Generated by CoffeeScript 1.3.3
(function() {
  var clean_up_db, clear_entity, entity_factory, insert_entity, set_up_db, set_up_entity_tables_for;

  entity_factory = require('../../support/core').core.entity_factory;

  set_up_entity_tables_for = function(entity_model) {
    return entity_factory.get(entity_model).sync();
  };

  insert_entity = function(entity_name, values_obj) {
    var instance;
    instance = entity_factory.create(entity_name, values_obj);
    return instance.save();
  };

  clear_entity = function(entity_name) {
    return entity_factory.get(entity_name).clear();
  };

  set_up_db = function(models_object) {
    var entities, entity_name, values, _results;
    _results = [];
    for (entity_name in models_object) {
      entities = models_object[entity_name];
      set_up_entity_tables_for(entity_name);
      _results.push((function() {
        var _i, _len, _results1;
        _results1 = [];
        for (_i = 0, _len = entities.length; _i < _len; _i++) {
          values = entities[_i];
          _results1.push(insert_entity(entity_name, values));
        }
        return _results1;
      })());
    }
    return _results;
  };

  clean_up_db = function(models_object) {
    var entity, values, _results;
    _results = [];
    for (entity in models_object) {
      values = models_object[entity];
      _results.push(clear_entity(entity));
    }
    return _results;
  };

  module.exports = {
    set_up_db: set_up_db,
    clean_up_db: clean_up_db
  };

}).call(this);
