// Generated by CoffeeScript 1.3.3
(function() {
  var methods;

  methods = {};

  methods.get_client = function(req, res) {
    return res.render('client.jade', {});
  };

  module.exports = {
    methods: methods,
    build_routes: function(app) {
      return app.get('/client', methods.get_client);
    }
  };

}).call(this);
