// Generated by CoffeeScript 1.3.3
(function() {
  var helper;

  helper = require('../support/core_helper');

  module.exports = function(app, io) {
    return helper.require_all_files_in(__dirname, app, io);
  };

}).call(this);
